name: Deploy Shopify Development Theme

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  shopify:
    name: Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build sources
        run: npm run parcel:build:css & npm run parcel:build:js

      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_DEVELOP_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --ignores=.themeignore
